services:
  db:
    image: "postgres:${DATABASE_VERSION}"
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ban-db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    image: "ban-berlinarchnet-web:${BAN_BERLINARCHNET_VERSION}"
    env_file:
      - .env
    user: "${USER_ID}:${GROUP_ID}"
    command: "bundle exec rails s -b 0.0.0.0 -p ${RAILS_PORT}"
    volumes:
      - .:/opt/ban-berlinarchnet
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
    depends_on:
      - db
volumes:
  ban-db-data:
