apiVersion: batch/v1
kind: Job
metadata:
  name: ban-berlinarchnet-dbmigrate-job
  namespace: ban-berlinarchnet-production
spec:
  template:
    spec:
      containers:
        - name: ban-berlinarchnet-dbmigrate
          image: mbraganca/ban-berlinarchnet-web:0.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ban-berlinarchnet-configmap
            - secretRef:
                name: ban-berlinarchnet-secret
          command: ["rails", "db:migrate"]
      restartPolicy: Never
  backoffLimit: 4
