apiVersion: v1
kind: Service
metadata:
  name: ban-berlinarchnet-service
  namespace: ban-berlinarchnet-production
spec:
  type: LoadBalancer
  selector:
    app: ban-berlinarchnet
  ports:
    - port: 80
      targetPort: 3000
